import random

from pystrich.datamatrix import DataMatrixEncoder

ADJECTIVES = [
    "used", "every", "large", "popular", "able", "basic", "known", "various",
    "several", "united", "hot", "useful", "mental", "scared", "old", "similar",
    "healthy", "medical", "federal", "entire", "strong", "actual", "poor",
    "happy", "cute", "helpful", "recent", "willing", "nice", "serious", "huge",
    "rare", "typical", "aware", "global", "legal", "capable", "foreign",
    "hungry", "severe", "unusual", "famous", "pure", "afraid", "obvious",
    "careful", "latter", "unhappy", "boring", "eastern", "logical", "strict",
    "civil", "former", "massive", "unfair", "visible", "alive", "angry",
    "lucky", "sorry", "ugly", "anxious", "curious", "inner", "sexual",
    "sudden", "unable", "weak", "wooden", "asleep", "decent", "guilty",
    "lonely", "mad", "nervous", "odd", "tall", "tiny", "other", "new", "just",
    "good", "any", "each", "own", "great", "another", "same", "free", "right",
    "still", "best", "public", "human", "local", "sure", "better", "general",
    "enough", "long", "small", "high", "certain", "little", "common", "next",
    "simple", "hard", "past", "big", "real", "major", "current", "left",
    "least", "natural", "short", "last", "main", "lower", "open", "special",
    "working", "true", "whole", "clear", "dry", "easy", "cold", "full", "low",
    "primary", "worth", "present", "close", "green", "late", "fit", "glad",
    "proper", "complex", "content", "due", "middle", "regular", "fast", "wide",
    "active", "safe", "visual", "wrong", "quick", "ready", "white", "direct",
    "extra", "junior", "pretty", "unique", "classic", "final", "overall",
    "private", "western", "alone", "perfect", "bright", "broad", "flat",
    "rich", "warm", "young", "heavy", "correct", "leading", "slow", "clean",
    "fresh", "normal", "secret", "tough", "brown", "cheap", "deep", "secure",
    "thin", "cool", "extreme", "exact", "fair", "fine", "formal", "remote",
    "total", "vast", "lost", "smooth", "dark", "double", "equal", "firm",
    "minor", "raw", "soft", "solid", "weird", "amazing", "annual", "busy",
    "dead", "false", "round", "sharp", "thick", "wise", "initial", "narrow",
    "nearby", "proud", "wild", "adult", "apart", "brief", "crazy", "prior",
    "rough", "sad", "sick", "strange", "illegal", "loud", "mobile", "nasty",
    "royal", "senior", "super", "tight", "upper", "yellow", "funny", "gross",
    "ill", "spare", "sweet", "usual", "brave", "calm", "dirty", "grand",
    "honest", "loose", "male", "quiet", "dear", "drunk", "empty", "female",
    "neat", "silly", "slight", "smart", "stupid",
]

NOUNS = [
    "people", "way", "art", "world", "map", "family", "health", "system",
    "meat", "year", "thanks", "music", "person", "method", "data", "food",
    "theory", "law", "bird", "power", "love", "nature", "fact", "idea", "area",
    "story", "media", "thing", "oven", "safety", "player", "video", "week",
    "exam", "movie", "policy", "series", "basis", "army", "camera", "paper",
    "child", "month", "truth", "goal", "news", "growth", "income", "user",
    "night", "disk", "energy", "nation", "road", "role", "soup", "math",
    "moment", "event", "wood", "office", "unit", "driver", "flight", "length",
    "cell", "dealer", "lake", "member", "phone", "scene", "death", "mood",
    "woman", "advice", "blood", "effort", "skill", "wealth", "city", "county",
    "depth", "estate", "heart", "photo", "recipe", "studio", "topic", "ad",
    "agency", "debt", "memory", "aspect", "steak", "union", "cancer", "entry",
    "region", "virus", "actor", "device", "drama", "engine", "hotel", "owner",
    "bath", "bread", "guest", "height", "mall", "sample", "cousin", "editor",
    "extent", "guitar", "leader", "mom", "singer", "tennis", "basket", "bonus",
    "church", "coffee", "dinner", "hair", "lab", "mode", "mud", "orange",
    "poetry", "police", "queen", "ratio", "sector", "song", "tooth", "town",
    "volume", "wife", "error", "farmer", "gate", "girl", "hall", "injury",
    "meal", "pie", "poem", "river", "son", "speech", "tea", "winner", "worker",
    "writer", "breath", "buyer", "chest", "cookie", "dad", "desk", "drawer",
    "honey", "insect", "king", "ladder", "menu", "piano", "potato", "salad",
    "sister", "tongue", "affair", "apple", "beer", "cheek", "client", "dirt",
    "ear", "gene", "hat", "lady", "pizza", "poet", "shirt", "sir", "tale",
    "throat", "uncle", "youth", "time", "work", "film", "water", "money",
    "while", "study", "game", "life", "form", "air", "day", "place", "number",
    "part", "field", "fish", "back", "heat", "hand", "job", "book", "end",
    "point", "type", "home", "value", "body", "market", "guide", "state",
    "radio", "course", "price", "size", "card", "list", "mind", "trade", "line",
    "care", "group", "risk", "word", "fat", "force", "key", "light", "name",
    "school", "top", "amount", "level", "order", "sense", "piece", "web",
    "boss", "sport", "fun", "house", "page", "term", "test", "answer", "sound",
    "focus", "matter", "kind", "soil", "board", "oil", "access", "garden",
    "range", "rate", "reason", "future", "site", "demand", "image", "case",
    "cause", "coast", "action", "age", "bad", "boat", "record", "result",
    "mouse", "cash", "class", "period", "plan", "store", "tax", "side", "space",
    "rule", "stock", "chance", "figure", "man", "model", "source", "earth",
    "design", "head", "rock", "salt", "act", "birth", "car", "dog", "object",
    "scale", "sun", "note", "profit", "rent", "speed", "style", "war", "bank",
    "craft", "half", "inside", "bus", "eye", "fire", "stress", "box", "frame",
    "issue", "step", "cycle", "face", "item", "metal", "paint", "review",
    "room", "screen", "view", "ball", "medium", "share", "black", "bottom",
    "choice", "gift", "impact", "shape", "tool", "wind", "career", "pot",
    "sign", "table", "task", "credit", "egg", "hope", "ice", "north", "square",
    "date", "effect", "link", "post", "star", "voice", "friend", "brush",
    "couple", "debate", "exit", "front", "lack", "living", "plant", "spot",
    "summer", "taste", "theme", "track", "wing", "brain", "button", "click",
    "desire", "foot", "gas", "notice", "rain", "wall", "base", "damage",
    "staff", "sugar", "target", "text", "animal", "author", "budget", "file",
    "ground", "lesson", "minute", "phase", "sky", "stage", "stick", "title",
    "bowl", "bridge", "club", "edge", "fan", "letter", "lock", "novel",
    "option", "pack", "park", "plenty", "skin", "sort", "weight", "baby",
    "carry", "dish", "factor", "fruit", "glass", "joint", "master", "muscle",
    "trip", "appeal", "chart", "gear", "ideal", "land", "log", "mother", "net",
    "party", "sale", "season", "signal", "spirit", "street", "tree", "wave",
    "belt", "bench", "copy", "drop", "path", "sea", "south", "status", "stuff",
    "ticket", "tour", "angle", "blue", "degree", "doctor", "dot", "dream",
    "duty", "essay", "father", "fee", "hour", "juice", "limit", "luck", "milk",
    "mouth", "peace", "pipe", "seat", "stable", "storm", "team", "trick", "bat",
    "beach", "blank", "catch", "chain", "cream", "crew", "detail", "gold",
    "kid", "mark", "match", "pain", "score", "screw", "sex", "shop", "shower",
    "suit", "tone", "window", "agent", "band", "block", "bone", "cap", "coat",
    "corner", "court", "cup", "door", "east", "finger", "garage", "hole",
    "hook", "layer", "lie", "manner", "nose", "rice", "tip", "winter", "bag",
    "battle", "bed", "bill", "bother", "cake", "code", "curve", "dress", "ease",
    "farm", "fight", "gap", "grade", "horror", "horse", "host", "loan", "nail",
    "noise", "pause", "phrase", "proof", "race", "relief", "sand", "smoke",
    "string", "towel", "west", "wheel", "wine", "arm", "aside", "bet", "blow",
    "border", "branch", "breast", "buddy", "bunch", "chip", "coach", "cross",
    "draft", "dust", "expert", "floor", "golf", "habit", "iron", "judge",
    "knife", "league", "mail", "mess", "native", "parent", "pin", "pool",
    "pound", "salary", "shame", "shoe", "silver", "tackle", "tank", "trust",
    "assist", "bake", "bar", "bell", "bike", "blame", "boy", "brick", "chair",
    "closet", "clue", "collar", "devil", "diet", "fear", "fuel", "glove",
    "jacket", "lunch", "nurse", "pace", "panic", "peak", "plane", "reward",
    "row", "shock", "spite", "spray", "till", "yard", "alarm", "bend", "bite",
    "blind", "bottle", "cable", "candle", "clerk", "cloud", "flower", "harm",
    "knee", "lawyer", "load", "mirror", "neck", "plate", "purple", "ruin",
    "ship", "skirt", "slice", "snow", "stroke", "switch", "trash", "tune",
    "zone", "anger", "award", "bid", "bitter", "boot", "bug", "camp", "candy",
    "carpet", "cat", "clock", "cow", "crack", "fault", "grass", "guy", "hell",
    "island", "joke", "jury", "leg", "lip", "mate", "motor", "nerve", "pen",
    "pride", "priest", "prize", "resort", "ring", "roof", "rope", "sail",
    "scheme", "script", "sock", "toe", "tower", "truck",
]

if __name__ == '__main__':
    print(len(ADJECTIVES) * len(NOUNS))

    for i in range(0, 500):
        code = random.choice(ADJECTIVES) + "-" + random.choice(NOUNS)
        print(code)
        DataMatrixEncoder(code).save(code + '.png')
